import { z } from "zod";
import type { Env } from "../types/env";

const identitySchema = z.object({
  PRIVACY_CONTROLLER_NAME: z.string().trim().min(2).max(200),
  PRIVACY_CONTACT_EMAIL: z.email().max(254),
  PRIVACY_POSTAL_ADDRESS: z.string().trim().min(5).max(500),
});

export function escapeHtml(value: string): string {
  return value.replace(/[&<>"']/g, (character) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[character]!);
}

export function privacyIdentity(env: Env) {
  return identitySchema.safeParse(env);
}

export function legalPage(title: string, content: string, status = 200): Response {
  const nonce = crypto.randomUUID().replaceAll("-", "");
  return new Response(`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="robots" content="noindex, nofollow"><title>${escapeHtml(title)} · MobDeals Automation</title><style nonce="${nonce}">
  :root{color:#182235;background:#f6f8fb;font-family:Inter,ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;font-size:17px;line-height:1.65;color-scheme:light}*{box-sizing:border-box}body{margin:0}header,main,footer{max-width:78ch;margin:auto;padding:24px}header{border-bottom:1px solid #e1e7f0}header>a{font-weight:750;text-decoration:none;color:#111a2c}nav{display:flex;flex-wrap:wrap;gap:8px 24px;margin-top:12px;font-size:.9rem}a{color:#1649b9;text-underline-offset:4px;overflow-wrap:anywhere}a:hover{color:#111a2c}main{padding-top:36px;padding-bottom:48px}h1{font-size:clamp(2rem,5vw,2.8rem);letter-spacing:-.025em;line-height:1.15;margin:0 0 18px;text-wrap:balance}h2{font-size:1.2rem;margin:32px 0 8px;line-height:1.3}p{margin:12px 0}li{margin-bottom:8px}small,.muted{color:#526077}footer{border-top:1px solid #e1e7f0;font-size:.85rem}form{margin-top:24px}label{display:block;font-weight:650;margin:18px 0 6px}input,textarea{display:block;width:100%;padding:12px;border:1px solid #738096;border-radius:8px;background:white;color:#182235;font:inherit}textarea{min-height:100px;resize:vertical}button{border:0;border-radius:8px;padding:13px 20px;background:#1649b9;color:white;font:inherit;font-weight:650;cursor:pointer;margin-top:20px}button:hover{background:#123987}a:focus-visible,input:focus-visible,textarea:focus-visible,button:focus-visible{outline:3px solid #2563eb;outline-offset:4px}::selection{background:#cdddff;color:#111a2c}.notice{padding:16px;background:#fff2db;border:1px solid #dab36f;border-radius:8px}.receipt{overflow-wrap:anywhere;font-family:ui-monospace,monospace}dl{display:grid;grid-template-columns:auto 1fr;gap:8px 20px}dt{font-weight:650}dd{margin:0}@media(max-width:480px){header,main,footer{padding-left:20px;padding-right:20px}dl{display:block}dd{margin-bottom:14px}}
  </style></head><body><header><a href="/">MobDeals Automation</a><nav aria-label="Policies"><a href="/privacy-policy">Privacy policy</a><a href="/data-deletion">User data deletion</a><a href="/terms">Terms of service</a></nav></header><main><h1>${escapeHtml(title)}</h1>${content}</main><footer>MobDeals Meta Automation Suite · <a href="/">Staff sign in</a></footer></body></html>`, {
    status,
    headers: {
      "content-type": "text/html; charset=utf-8",
      "cache-control": "no-store",
      "referrer-policy": "no-referrer",
      "x-content-type-options": "nosniff",
      "x-frame-options": "DENY",
      "content-security-policy": `default-src 'none'; style-src 'nonce-${nonce}'; form-action 'self'; base-uri 'none'; frame-ancestors 'none'`,
    },
  });
}

export function policyPage(path: string, env: Env): Response | null {
  if (!["/privacy-policy", "/privacy", "/data-deletion", "/terms", "/terms-of-service"].includes(path)) return null;
  const identity = privacyIdentity(env);
  const draft = identity.success ? "" : '<p class="notice"><strong>Draft notice.</strong> The operator’s legal identity and privacy contact are awaiting confirmation. This notice is not ready for publication.</p>';
  const contact = identity.success
    ? `<p><strong>${escapeHtml(identity.data.PRIVACY_CONTROLLER_NAME)}</strong><br>${escapeHtml(identity.data.PRIVACY_POSTAL_ADDRESS)}<br>Privacy contact: <a href="mailto:${escapeHtml(identity.data.PRIVACY_CONTACT_EMAIL)}">${escapeHtml(identity.data.PRIVACY_CONTACT_EMAIL)}</a></p>`
    : "<p>The operator must configure a monitored privacy contact and postal address before publication.</p>";
  const status = identity.success ? 200 : 503;
  const date = "<p class=\"muted\">Last updated: 11 September 2026</p>";

  if (path === "/data-deletion") return legalPage("User data deletion", `${draft}${date}
    <p>You can ask us to delete personal data held by MobDeals Automation without creating an account or signing in.</p>
    <h2>Send a deletion request</h2><p>Use the form below or contact us directly. A Facebook profile, comment link, or the approximate date of a Messenger conversation helps us find your records. Do not send a password, access token, payment details, or identity document.</p>${contact}
    <form method="post" action="/data-deletion"><label for="contact">Email for your request</label><input id="contact" name="contact" type="email" autocomplete="email" maxlength="254" required aria-describedby="contact-help"><small id="contact-help">We use this only to verify and respond to your request.</small><label for="reference">Facebook or Messenger reference</label><textarea id="reference" name="reference" maxlength="1000" required aria-describedby="reference-help"></textarea><small id="reference-help">For example, a link to your comment, or your profile name and when you contacted MobDeals.</small><button type="submit">Request data deletion</button></form>
    <h2>What happens next</h2><ol><li>You receive a private status link. Save it; anyone with the link can see the request’s status.</li><li>We verify that the request concerns your data, normally through the existing Facebook or Messenger conversation. We request only the information reasonably needed for verification.</li><li>We remove verified matching records from the active application database, including webhook payloads, comments and replies, Messenger contacts, conversations and messages, and sales leads.</li></ol>
    <p>We aim to act without undue delay and respond within one calendar month of receiving your request. If a lawful extension is necessary because of complexity or the number of requests, we will explain it within that first month; an extension can be up to two further months. If we cannot fulfill a request, we explain why and how you can challenge the decision.</p>
    <h2>Requests through Facebook</h2><p>If this app appears in your Facebook Apps and websites or Business integrations settings, remove it and use any available option to request deletion. If Facebook sends us a deletion request, its confirmation link shows our progress. Removing access alone does not always send a deletion request; you can also use this form.</p>
    <h2>Deletion scope and retained records</h2><p>This process deletes this service’s copies. It does not delete your Facebook account, content held independently by Meta, or records held by other businesses. You can remove original Facebook content through Meta’s own controls. Staff account requests and any records outside this application are handled directly by the privacy contact.</p>
    <p>After completion, request contact and reference details are cleared. A minimal receipt remains for 90 days. For 90 days we also retain restricted hashes of verified identifiers to prevent webhook retries from recreating deleted records. These are pseudonymous records, not anonymous data. Isolated backup copies expire under the provider’s configured backup schedule and must not be restored to active use without reapplying deletion. We explain any specific legal retention exception to you.</p>
    <p>For access, correction, portability, restriction, objection, or withdrawal of consent, contact us using the details above. See the <a href="/privacy-policy">privacy policy</a> for your rights and how to complain.</p>`, status);

  if (path === "/terms" || path === "/terms-of-service") return legalPage("Terms of service", `${draft}${date}
    <h2>Service and operator</h2><p>MobDeals Meta Automation Suite supports staff management of the MobDeals Kenya Facebook Page, including reviewing and scheduling product posts and receiving Page and Messenger events.</p>${contact}
    <h2>Authorized use</h2><p>Staff access is by invitation. Use only accounts, Pages, content, and customer information you are authorized to manage. Keep credentials private, use required multi-factor authentication, and report suspected unauthorized access to the operator promptly. Do not use the service for spam, harassment, unlawful processing, or attempts to bypass access controls.</p>
    <h2>Meta integration</h2><p>Use of Facebook and Messenger is also subject to Meta’s applicable terms and platform policies. Permissions and platform availability can change. Staff must review content and permissions before enabling automation; the service does not guarantee publication or message delivery.</p>
    <h2>Customer information</h2><p>Process personal data only for the disclosed purposes, with an appropriate legal basis. Do not upload identity documents, payment credentials, or sensitive personal information to product content or customer notes. Our <a href="/privacy-policy">privacy policy</a> explains the data we process. You can <a href="/data-deletion">request deletion</a> without agreeing to these terms.</p>
    <h2>Availability and changes</h2><p>The operator may pause automation or restrict access to protect users or maintain the service. Product information and draft posts require staff review for accuracy. Material changes to these terms will be communicated to affected staff, with an updated date on this page.</p>
    <h2>Rights and contact</h2><p>These terms do not waive mandatory consumer or data protection rights, create consent to marketing, or replace a separate service agreement with the operator. Send questions or complaints to the contact above.</p>`, status);

  return legalPage("Privacy policy", `${draft}${date}
    <h2>Who is responsible</h2><p>This notice covers MobDeals Meta Automation Suite, the staff operations service for the MobDeals Kenya Facebook Page. The controller determines why and how personal data is used:</p>${contact}
    <p>It covers people interacting with the Page or Messenger, staff using the dashboard, and people making privacy requests. Meta independently handles data on its own services under its own privacy policy.</p>
    <h2>Information we receive</h2><ul><li><strong>Page and Messenger events:</strong> identifiers supplied by Meta, profile or display names where supplied, comments, message text, timestamps, event metadata, and attachment references contained in webhook deliveries.</li><li><strong>Customer service records:</strong> where the relevant workflows are enabled, conversations, replies, handoff reasons, product interests, budgets, preferences, and contact or delivery information you choose to provide. Comment and Messenger reply automation are not enabled in the current release.</li><li><strong>Staff records:</strong> email, display name, role, account status, authentication and MFA records, sign-in times, and administrative audit history.</li><li><strong>Privacy requests:</strong> your contact details, reference information or Meta app-scoped identifier, request dates, status, and limited verification and completion records.</li><li><strong>Technical records:</strong> operational event identifiers and error categories. Hosting and authentication providers may process IP addresses and device information for delivery, authentication, and security.</li></ul>
    <p>We obtain interaction data from Meta, staff details from you or the inviting administrator, and request details directly from you or Meta. Please do not send payment credentials, identity documents, or sensitive personal information.</p>
    <h2>Purposes and legal bases</h2><p>Where GDPR applies, we use information needed to respond to a product inquiry or take steps you request before a contract under Article 6(1)(b). We use relevant Page interactions, staff access controls, and limited technical and audit records for our legitimate interests in operating customer support, managing authorized publishing, and preventing misuse under Article 6(1)(f), balanced against your rights. We process rights requests and records necessary to comply with applicable data protection duties under Article 6(1)(c).</p>
    <p>We do not treat contacting the Page or accepting terms as consent to unrelated marketing. Any processing that requires consent must have a separate, specific choice that can be withdrawn. Providing inquiry details is voluntary; without relevant contact or reference details, we may be unable to respond or locate your records. Staff authentication details are required for dashboard access.</p>
    <h2>Sharing and international processing</h2><p>Access is restricted to authorized staff and service providers needed to run the service: Meta for Facebook and Messenger, Cloudflare for hosting and delivery, and Supabase for the database, staff authentication, and product-image storage. We do not sell personal data or use it to train AI models in this application. Product images intended for publication are publicly accessible and must not contain private customer information.</p>
    <p>The operator is based in Kenya; providers may process data in other countries. Where GDPR restricts an international transfer, the operator must establish an applicable adequacy decision or appropriate safeguards, such as EU Standard Contractual Clauses with any required additional measures, before that transfer. Contact us for the applicable destinations, safeguards, or a copy of relevant safeguards. We may also disclose information where a specific legal obligation requires it.</p>
    <h2>Retention</h2><ul><li>Raw Meta webhook deliveries: up to 30 days.</li><li>Comments and replies, Messenger messages and inactive contacts or conversations, and sales leads: up to 90 days, with active conversation relationships assessed using their latest interaction.</li><li>Application audit and failure logs: up to 30 days.</li><li>Open deletion requests: until resolved, with a response due within one calendar month. Contact and reference information is cleared on completion; minimal completed receipts and replay-suppression hashes expire after 90 days.</li><li>Staff accounts: while access is required, followed by an offboarding review and deletion of unnecessary account data. Hosting, authentication logs, and backups follow the provider settings maintained by the operator.</li></ul>
    <p>Scheduled cleanup enforces the application database limits. A verified deletion request can remove data sooner. Provider backups require separate lifecycle controls; if restored, deletion must be reapplied before use. Any legal retention exception must be limited to necessary data, documented, and explained to the affected person where required.</p>
    <h2>Your choices and rights</h2><p>Where applicable, you can request access, correction, erasure, restriction, or a portable copy of eligible information, object to processing based on legitimate interests, and withdraw consent without affecting earlier lawful processing. You can object to direct marketing at any time. We do not make solely automated decisions with legal or similarly significant effects about you in this application.</p>
    <p>Use the <a href="/data-deletion">data deletion page</a> or contact us for any privacy request. You do not need a staff account. We normally respond free of charge without undue delay and within one calendar month; we explain any lawful extension or refusal and your options to challenge it. We may ask for proportionate verification to protect your data.</p>
    <p>You can complain to your competent EU/EEA supervisory authority, including in your habitual residence, workplace, or where an alleged infringement occurred. You can also contact Kenya’s <a href="https://www.odpc.go.ke/">Office of the Data Protection Commissioner</a>, or the UK ICO where applicable. You do not have to contact us first.</p>
    <h2>Browser storage and security</h2><p>The public policy and deletion pages do not use analytics or advertising cookies. The staff dashboard stores the Supabase authentication session in browser storage to maintain sign-in. Hosting providers may use essential security mechanisms. To limit abuse of the deletion form, we keep a daily keyed hash of the connection IP address with a request counter for up to one day. We use encrypted connections, restricted database access, verified webhook signatures, and permission checks. Do not share a deletion status link; it acts as a private receipt.</p>
    <h2>Children and changes</h2><p>This business service is not directed at children. Contact us if a child’s data has been provided so we can review and remove it where appropriate. We update this notice when processing changes and communicate material changes through appropriate service channels.</p>`, status);
}
